config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lunch_group_users
  resources :lunch_groups do 
  	collection do 
  		get 'start_lunch'
    end

    member do 
      get 'get_partial'
    end
  end


  resources :users do 
  	collection do 
  		post 'manual_create'
  		post 'manual_login'
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#login'
end

app/models/lunch_group.rb
class LunchGroup < ApplicationRecord
	has_many :lunch_group_users

	def self.current_groups
		# select groups that currently have users in them
		select {|e| e.lunch_group_users.count > 0}
	end

	def self.find_records_for(user)
		select do |e| 
			user_array = JSON.parse(e.users_in_this_group)
			user_array.include?(user.id)
		end
	end

	def lunch_group_users_list
		if lunch_group_users.empty?
			out = JSON.parse(users_in_this_group).map { |e| User.find(e) }
		else
			out = lunch_group_users.map { |e| e.user }
		end
		out
	end

	def is_past?
		lunch_group_users.empty?
	end

	def number_people
		lunch_group_users.count
	end

	def all_confirmed?
		lunch_group_users.all? { |e| e.confirmed }
	end

	def add_another(user)
    people = JSON.parse(users_in_this_group)
    people << user.id
    update_attributes(:users_in_this_group => people.to_json)
	end

end

app/controllers/lunch_groups_controller.rb
class LunchGroupsController < ApplicationController
  before_action :set_lunch_group, only: [:show, :edit, :update, :destroy, :get_partial]

  # GET /lunch_groups
  # GET /lunch_groups.json
  def index
    @lunch_groups = LunchGroup.current_groups
  end

  # GET /lunch_groups/1
  # GET /lunch_groups/1.json
  def show
  end

  # GET /lunch_groups/new
  def new
    @lunch_group = LunchGroup.new
  end

  # GET /lunch_groups/1/edit
  def edit
  end


  def start_lunch
    # clear current LunchGroupUser table
    LunchGroupUser.destroy_all
    # Sort all current users into groups
    flash[:error] = ''
    User.all.each_slice(4) do |group|
      # IF anyone is eating alone, join them to another group
      if group.size <= 2
        lunch_group = LunchGroup.current_groups.shuffle.first
        #  TODO: fix this to even distribute more than 4 users in group
        while lunch_group.lunch_group_users.count < 5
          lunch_group = LunchGroup.current_groups.shuffle.first
        end
        group.each do |user|
          lunch_group.add_another(user)
        end
      else
        # Make sure group has permanent record of its users
        lunch_group = LunchGroup.new(:users_in_this_group => group.map { |e| e.id }.to_json)
      end

      if lunch_group.save
        group.each do |user|
          join_record = LunchGroupUser.new(:user_id => user.id, :lunch_group_id => lunch_group.id)
          if !join_record.save
            flash[:error] += join_record.errors.full_messages.join(', ')
          end
        end
      end
    end

    # Redirect to index page
    redirect_to lunch_groups_path
  end

  def end_lunch
    # clear out lunch_group_users table
  end

  # POST /lunch_groups
  # POST /lunch_groups.json
  def create
    @lunch_group = LunchGroup.new(lunch_group_params)

    respond_to do |format|
      if @lunch_group.save
        format.html { redirect_to @lunch_group, notice: 'Lunch group was successfully created.' }
        format.json { render :show, status: :created, location: @lunch_group }
      else
        format.html { render :new }
        format.json { render json: @lunch_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lunch_groups/1
  # PATCH/PUT /lunch_groups/1.json
  def update
    # Find the lunch_group_users for this group with the current user
    invite = LunchGroupUser.find_invite(current_user, @lunch_group)
    if invite.nil?
      render :json => { :success => false, :message => 'No such invite', :lunch_group_id => @lunch_group.id }
    else
      case params['this_action']
      when 'confirm'
        invite.confirmed = true
      when 'cancel'
        invite.confirmed = false
      when 'update_location'
        @lunch_group.location = lunch_group_params['type_of_food'] 
        @lunch_group.save       
      end

      if invite.save
        render :json => { :success => true, :message => '', :lunch_group_id => @lunch_group.id }
      else
        render :json => { :success => false, :message => invite.errors.full_messages.join(', '), :lunch_group_id => @lunch_group.id }
      end
    end
  end

  def get_partial
    render :partial => 'lunch_groups/lunch_group_list_item', :locals => { :lunch_group => @lunch_group }
  end

  # DELETE /lunch_groups/1
  # DELETE /lunch_groups/1.json
  def destroy
    @lunch_group.destroy
    respond_to do |format|
      format.html { redirect_to lunch_groups_url, notice: 'Lunch group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lunch_group
      @lunch_group = LunchGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lunch_group_params
      params.require(:lunch_group).permit(:location)
    end
  end

app/helpers/lunch_groups_helper.rb
module LunchGroupsHelper
end

app/views/lunch_groups/_form.html.erb
<%= form_for(lunch_group) do |f| %>
  <% if lunch_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lunch_group.errors.count, "error") %> prohibited this lunch_group from being saved:</h2>

      <ul>
      <% lunch_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lunch_groups/_lunch_group_list_item.html.erb
    <li class="list-group-item d-flex justify-content-between align-items-center" style="background-color: <%= lunch_group.all_confirmed? ? 'yellow' : 'transparent' %>;">
	    <% if lunch_group.lunch_group_users_list.include?(current_user) %>
			  <% if !lunch_group.is_past? %>
		    	<h4>Choose for group</h4>
	      	<% if lunch_group.location.nil? %>
						<form id='choose-rest' group-id='<%= lunch_group.id %>'>
							<input type="hidden" name="this_action" value='update_location'>
							<div class="form-group">
								<select class="form-control" name="lunch_group[type_of_food]">
									<!-- TODO:  get this from yelp -->
									<option value="Thai Food">Thai Food</option>
									<option value="Pizza">Pizza</option>
									<option value="Greek">Greek</option>
									<option value="Food Trucks">Food Trucks</option>
								</select>
							</div>
							<button type="submit" name="confirm" class="btn btn-primary">CONFIRM</button>
						</form>
			    <% else %>
				    <h4><%= lunch_group.location ? lunch_group.location : 'No restaurant choosen' %></h4>
			    <% end %>
		    	<% if LunchGroupUser.find_invite(current_user,lunch_group).try(:confirmed) %>
			    	<a href="#" class="btn btn-danger btn-md confirm-this" this_action='cancel' group-id='<%= lunch_group.id %>'>Cancel</a>
			    <% else %>
			    	<a href="#" class="btn btn-primary btn-md confirm-this" this_action='confirm' group-id='<%= lunch_group.id %>'>Confirm</a>
			    <% end %>
		    <% end %>
	    <% end %>
    	<ul>
        <% lunch_group.lunch_group_users_list.each do |user| %>
	        <li>
		        <a href='<%= user_path(:id => user.id) %>'><%= user.name %></a>
	        </li>
        <% end %>
    	</ul>
        <span class="badge badge-primary badge-pill"><%= lunch_group.is_past? ? 'past' : lunch_group.number_people %></span>
    </li>

app/views/lunch_groups/edit.html.erb
<h1>Editing Lunch Group</h1>

<%= render 'form', lunch_group: @lunch_group %>

<%= link_to 'Show', @lunch_group %> |
<%= link_to 'Back', lunch_groups_path %>

app/views/lunch_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current Lunch Groups</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <ul class="list-group">
      <% @lunch_groups.each do |lunch_group| %>
        <%= render :partial => 'lunch_group_list_item', :locals => {:lunch_group => lunch_group} %>
      <% end %>
    </ul>
  </tbody>
</table>

<br>

<%= link_to 'New Lunch Group', new_lunch_group_path %>

app/views/lunch_groups/new.html.erb
<h1>New Lunch Group</h1>

<%= render 'form', lunch_group: @lunch_group %>

<%= link_to 'Back', lunch_groups_path %>

app/views/lunch_groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_lunch_group_path(@lunch_group) %> |
<%= link_to 'Back', lunch_groups_path %>