config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lunch_group_users
  resources :lunch_groups do 
  	collection do 
  		get 'start_lunch'
    end

    member do 
      get 'get_partial'
    end
  end


  resources :users do 
  	collection do 
  		post 'manual_create'
  		post 'manual_login'
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#login'
end

app/models/lunch_group_user.rb
class LunchGroupUser < ApplicationRecord
	belongs_to :user
	belongs_to :lunch_group

	validates_uniqueness_of :user_id, :scope => :lunch_group_id

	def self.find_invite(user,group)
		select{ |e| e.user_id == user.id && e.lunch_group_id == group.id }.first
	end
end

app/controllers/lunch_group_users_controller.rb
class LunchGroupUsersController < ApplicationController
  before_action :set_lunch_group_user, only: [:show, :edit, :update, :destroy]

  # GET /lunch_group_users
  # GET /lunch_group_users.json
  def index
    @lunch_group_users = LunchGroupUser.all
  end

  # GET /lunch_group_users/1
  # GET /lunch_group_users/1.json
  def show
  end

  # GET /lunch_group_users/new
  def new
    @lunch_group_user = LunchGroupUser.new
  end

  # GET /lunch_group_users/1/edit
  def edit
  end

  # POST /lunch_group_users
  # POST /lunch_group_users.json
  def create
    @lunch_group_user = LunchGroupUser.new(lunch_group_user_params)

    respond_to do |format|
      if @lunch_group_user.save
        format.html { redirect_to @lunch_group_user, notice: 'Lunch group user was successfully created.' }
        format.json { render :show, status: :created, location: @lunch_group_user }
      else
        format.html { render :new }
        format.json { render json: @lunch_group_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lunch_group_users/1
  # PATCH/PUT /lunch_group_users/1.json
  def update
    
  end

  # DELETE /lunch_group_users/1
  # DELETE /lunch_group_users/1.json
  def destroy
    # TODO: people can be kicked out of grops

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lunch_group_user
      @lunch_group_user = LunchGroupUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lunch_group_user_params
      params.fetch(:lunch_group_user, {})
    end
end

app/helpers/lunch_group_users_helper.rb
module LunchGroupUsersHelper
end

app/views/lunch_group_users/_form.html.erb
<%= form_for(lunch_group_user) do |f| %>
  <% if lunch_group_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lunch_group_user.errors.count, "error") %> prohibited this lunch_group_user from being saved:</h2>

      <ul>
      <% lunch_group_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lunch_group_users/edit.html.erb
<h1>Editing Lunch Group User</h1>

<%= render 'form', lunch_group_user: @lunch_group_user %>

<%= link_to 'Show', @lunch_group_user %> |
<%= link_to 'Back', lunch_group_users_path %>

app/views/lunch_group_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lunch Group Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lunch_group_users.each do |lunch_group_user| %>
      <tr>
        <td><%= link_to 'Show', lunch_group_user %></td>
        <td><%= link_to 'Edit', edit_lunch_group_user_path(lunch_group_user) %></td>
        <td><%= link_to 'Destroy', lunch_group_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lunch Group User', new_lunch_group_user_path %>

app/views/lunch_group_users/new.html.erb
<h1>New Lunch Group User</h1>

<%= render 'form', lunch_group_user: @lunch_group_user %>

<%= link_to 'Back', lunch_group_users_path %>

app/views/lunch_group_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_lunch_group_user_path(@lunch_group_user) %> |
<%= link_to 'Back', lunch_group_users_path %>