config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lunch_group_users
  resources :lunch_groups do 
  	collection do 
  		get 'start_lunch'
    end

    member do 
      get 'get_partial'
    end
  end


  resources :users do 
  	collection do 
  		post 'manual_create'
  		post 'manual_login'
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#login'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AptListingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
	  	<nav class="navbar navbar-expand-sm navbar-dark" style="background: #445229;">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
				</button>

				<!-- Brand -->
				<a class="navbar-brand" href="<%= user_path(:id => current_user.id)%>">
					<img src='<%= current_user.avatar_url %>' class='media-object img-rounded avatar' style='padding-bottom: 2%; margin: 0 auto;'>
				</a>

				<!-- Links -->
				<div class="collapse navbar-collapse" id="nav-content">   
				<ul class="navbar-nav">
					<li class="nav-item">
					<!-- TODO: make this admin only -->
					<a href="<%= start_lunch_lunch_groups_path %>" class='nav-link'>Start Lunch</a>
					</li>
					<li class="nav-item">
					<a href="<%= user_path(:id => current_user.id)%>" class='nav-link'>My Groups</a>
					</li>
					<li class="nav-item">
					<a href="<%= lunch_groups_path %>" class='nav-link'>Current Groups</a>
					</li>

				</ul>
				<div style="float: right;">
					<%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-md logout-button') %>
				</div>

			</nav>
  	<% end %>

     <% if flash[:error] && flash[:error] != "" %>
      <div class="error-message">
        <%= flash[:error] %>
      </div>

      <script type="text/javascript">
        setTimeout(function(){
          $('.error-message').fadeOut(1000);
        },2000)
      </script>
    <% end %>
  	<% if current_user %>
		<div class="login-window" style="width: 100%;background-color: transparent;">
			<div class="login-body" style="width: 100%;background-color: transparent; padding-left: 0%;">
		    <%= yield %>
			</div>
		</div>
  	<% else %>
		    <%= yield %>
  	<% end %>
  </body>

  <script type="text/javascript">
  	$('body').on('click', '.confirm-this', function(event) {
  		event.preventDefault();
  		var group_id = $(this).attr('group-id');
  		var action = $(this).attr('this_action');
  		$.ajax({
  			url: '/lunch_groups/' + group_id,
  			data: {this_action: action},
  			type: 'patch',
  		})
  		.done(function(data) {
  			updateDOM(data);
  		})
  		
  	});

  	$('body').on('submit', 'form#choose-rest', function(event) {
  		event.preventDefault();
  		var group_id = $(this).attr('group-id');
  		var action = $(this).attr('this_action');
  		$.ajax({
  			url: '/lunch_groups/' + group_id,
				data: $(this).serialize(),
  			type: 'patch'
  		})
  		.done(function(data) {
  			updateDOM(data);
  		})
  	});

  	function updateDOM(data) {
  			if (data.success) {
  				element = $('.list_item_for_group_' + data.lunch_group_id);
  				data_el = data.lunch_group_id;
  				$.ajax({
  					url: '/lunch_groups/' + data.lunch_group_id + '/get_partial',
  				})
  				.done(function(data) {
		  			element.html(data);
  				});
  			} else {
  				$(".error-message").text(data.message);
  				$(".error-message").fadeIn(1000, function() {
		  			setTimeout(function(){
		          $('.error-message').fadeOut(1000);
		        },2000)
  				});
  			}
  		
  	}
  </script>
</html>